//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 11:42:22 AM CET 
//


package org.highmed.dsf.atna.message;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import org.highmed.dsf.atna.message.EventID;
import org.highmed.dsf.atna.message.EventIdentificationContents;
import org.highmed.dsf.atna.message.EventTypeCode;


/**
 * <p>Java class for EventIdentificationContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventIdentificationContents"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}EventID"/&gt;
 *         &lt;element ref="{}EventTypeCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}EventOutcomeDescription" minOccurs="0"/&gt;
 *         &lt;element name="PurposeOfUse" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attGroup ref="{}CodedValueType"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="EventActionCode"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="C"/&gt;
 *             &lt;enumeration value="R"/&gt;
 *             &lt;enumeration value="U"/&gt;
 *             &lt;enumeration value="D"/&gt;
 *             &lt;enumeration value="E"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="EventDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="EventOutcomeIndicator" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="0"/&gt;
 *             &lt;enumeration value="4"/&gt;
 *             &lt;enumeration value="8"/&gt;
 *             &lt;enumeration value="12"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventIdentificationContents", propOrder = {
    "eventID",
    "eventTypeCode",
    "eventOutcomeDescription",
    "purposeOfUse"
})
public class EventIdentificationContents {

    @XmlElement(name = "EventID", required = true)
    protected EventID eventID;
    @XmlElement(name = "EventTypeCode")
    protected List<EventTypeCode> eventTypeCode;
    @XmlElement(name = "EventOutcomeDescription")
    protected String eventOutcomeDescription;
    @XmlElement(name = "PurposeOfUse")
    protected List<EventIdentificationContents.PurposeOfUse> purposeOfUse;
    @XmlAttribute(name = "EventActionCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eventActionCode;
    @XmlAttribute(name = "EventDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventDateTime;
    @XmlAttribute(name = "EventOutcomeIndicator", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eventOutcomeIndicator;

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setEventID(EventID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the eventTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventTypeCode }
     * 
     * 
     */
    public List<EventTypeCode> getEventTypeCode() {
        if (eventTypeCode == null) {
            eventTypeCode = new ArrayList<EventTypeCode>();
        }
        return this.eventTypeCode;
    }

    /**
     * Gets the value of the eventOutcomeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventOutcomeDescription() {
        return eventOutcomeDescription;
    }

    /**
     * Sets the value of the eventOutcomeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventOutcomeDescription(String value) {
        this.eventOutcomeDescription = value;
    }

    /**
     * Gets the value of the purposeOfUse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purposeOfUse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurposeOfUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventIdentificationContents.PurposeOfUse }
     * 
     * 
     */
    public List<EventIdentificationContents.PurposeOfUse> getPurposeOfUse() {
        if (purposeOfUse == null) {
            purposeOfUse = new ArrayList<EventIdentificationContents.PurposeOfUse>();
        }
        return this.purposeOfUse;
    }

    /**
     * Gets the value of the eventActionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventActionCode() {
        return eventActionCode;
    }

    /**
     * Sets the value of the eventActionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventActionCode(String value) {
        this.eventActionCode = value;
    }

    /**
     * Gets the value of the eventDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventDateTime() {
        return eventDateTime;
    }

    /**
     * Sets the value of the eventDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventDateTime(XMLGregorianCalendar value) {
        this.eventDateTime = value;
    }

    /**
     * Gets the value of the eventOutcomeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventOutcomeIndicator() {
        return eventOutcomeIndicator;
    }

    /**
     * Sets the value of the eventOutcomeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventOutcomeIndicator(String value) {
        this.eventOutcomeIndicator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attGroup ref="{}CodedValueType"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PurposeOfUse {

        @XmlAttribute(name = "csd-code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String csdCode;
        @XmlAttribute(name = "codeSystemName", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String codeSystemName;
        @XmlAttribute(name = "displayName")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String displayName;
        @XmlAttribute(name = "originalText", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String originalText;

        /**
         * Gets the value of the csdCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsdCode() {
            return csdCode;
        }

        /**
         * Sets the value of the csdCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsdCode(String value) {
            this.csdCode = value;
        }

        /**
         * Gets the value of the codeSystemName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeSystemName() {
            return codeSystemName;
        }

        /**
         * Sets the value of the codeSystemName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeSystemName(String value) {
            this.codeSystemName = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Gets the value of the originalText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalText() {
            return originalText;
        }

        /**
         * Sets the value of the originalText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalText(String value) {
            this.originalText = value;
        }

    }

}
